# 数据库连接设置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/JingJuSi?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: Ssgreentee23



  # 设置全局日期格式,如果设置这个格式,则代码中@DateTimeFormat(pattern = "dd/MM/yyyy") 无效!!
  mvc:
    format:
      date: yyyy-MM-dd
server:
  port: 8000
  servlet:
    encoding:
      charset: utf-8



# Mybatis 配置
mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml,mybatis/mapper/extend/*.xml
  #mapper-locations: classpath:/mybatis/mapper/*.xml,classpath:/mybatis/mapper/extend/*.xml;
  #mapper-locations: classpath:/mybatis/mapper/**/.xml;

#
logging:
  level:
    com.saicfinance.shixi.mapper: debug
